# -*- mode: ruby -*-
# vi: set ft=ruby :

cpu = "2"
ram = "1024"
hostname = "pinneberg.freifunk.site"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

	if Vagrant.has_plugin?('vagrant-librarian-puppet')
    	config.librarian_puppet.placeholder_filename = ".gitkeep"
 	else
		puts 'No vagrant-librarian-puppet plugin installed.'
	end

	config.vm.hostname = "#{hostname}"
	
	config.ssh.forward_agent = true
 	config.ssh.shell = "/bin/bash --login"
	
	if Vagrant.has_plugin?('vagrant-hostmanager')
    	config.hostmanager.enabled = true
    	config.hostmanager.manage_host = true
    	config.hostmanager.aliases = "www.#{hostname}"
    else
		puts 'No vagrant-hostmanager plugin installed.'	
  	end
  	
	# Enable provisioning with a shell script. Additional provisioners such as
	# Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
	# documentation for more information about their specific syntax and use.
	config.vm.provision "shell", inline: <<-SHELL
		sudo apt-get update
		sudo apt-get install -y puppet
	SHELL
 
	# Enable the Puppet provisioner, with will look in manifests
	config.vm.provision :puppet do |puppet|
	    puppet.manifests_path = "manifests"
	    puppet.manifest_file = "default.pp"
	    puppet.options = '--verbose'
	    puppet.module_path = "modules"
	end


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/contrib-jessie64"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.10"
  

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/var/www", :owner => "www-data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--cpus", "#{cpu}"]
    v.customize ["modifyvm", :id, "--memory", "#{ram}"]
    v.customize ["modifyvm", :id, "--name", "#{hostname}"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

end
