base: 'https://helgoland.freifunk.net'
baseVariants:
  -
    base: '//helgoland.freifunk.net.local'
    condition: 'applicationContext == "Development"'
errorHandling: { }
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
  -
    title: Englisch
    enabled: true
    languageId: '1'
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
rootPageId: 123
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      .html: 0
      freifunk-api.json: 202001192011
      sitemap.xml: 1533906435
  RssFeed:
    type: PageType
    limitToPages:
      - 135
    map:
      .rss: 200
  NodeAbo:
    type: Extbase
    extension: 'ffpi_node_updates'
    plugin: Nodeabo
    routes:
      -
        routePath: '/confirm/{email}/{secret}'
        _controller: 'Abo::cofirm'
        _arguments:
          email: email
          secret: secret
      -
        routePath: '/unsubscribe/{email}/{secret}'
        _controller: 'Abo::removeForm'
        _arguments:
          email: aboRemoveDemand/email
          secret: aboRemoveDemand/secret
      -
        routePath: /subscribe
        _controller: 'Abo::create'
    defaultController: 'Abo::new'
routes:
  -
    route: favicon.ico
    type: uri
    source: '/typo3conf/ext/ffpi_helgo_theme/Resources/Public/favicon.ico'
  -
    route: favicon.svg
    type: uri
    source: '/typo3conf/ext/ffpi_helgo_theme/Resources/Public/favicon.svg'
