base: 'https://pinneberg.freifunk.net'
baseVariants:
  -
    base: '//pinneberg.freifunk.net.local'
    condition: 'applicationContext == "Development"'
  -
    base: '//www.ffpi'
    condition: 'getenv("HTTP_HOST") == "www.ffpi"'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=41'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: 0
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ltr
    flag: de
  -
    title: Englisch
    enabled: true
    languageId: 1
    base: /en/
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-US
    direction: ltr
    fallbackType: fallback
    fallbacks: '0'
    flag: en-us-gb
  -
    title: Norwegisch
    enabled: true
    languageId: 2
    base: /no/
    typo3Language: no
    locale: nb_NO.UTF-8
    iso-639-1: no
    navigationTitle: Norsk
    hreflang: nb-NO
    direction: ltr
    fallbackType: fallback
    fallbacks: '1,0'
    flag: bv
  -
    title: Dänisch
    enabled: true
    languageId: 3
    base: /dk/
    typo3Language: dk
    locale: dk_DK.UTF-8
    iso-639-1: no
    navigationTitle: Dansk
    hreflang: nb-NO
    direction: ltr
    fallbackType: fallback
    fallbacks: '1,0'
    flag: dk
  -
    title: Ukrainisch
    enabled: true
    languageId: 4
    base: /ua/
    typo3Language: uk
    locale: uk_UA.UTF-8
    iso-639-1: uk
    navigationTitle: Українська
    hreflang: uk-UA
    direction: ltr
    fallbackType: fallback
    fallbacks: '1,0'
    flag: ua
rootPageId: 1
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    map:
      .html: 0
      freifunk-api.json: 202001192011
      sitemap.xml: 1533906435
  RssFeed:
    type: PageType
    limitToPages:
      - 5
    map:
      .rss: 200
  NodeAbo:
    type: Extbase
    extension: 'ffpi_node_updates'
    plugin: Nodeabo
    routes:
      -
        routePath: '/confirm/{email}/{secret}'
        _controller: 'Abo::cofirm'
        _arguments:
          email: email
          secret: secret
      -
        routePath: '/unsubscribe/{email}/{secret}'
        _controller: 'Abo::removeForm'
        _arguments:
          email: aboRemoveDemand/email
          secret: aboRemoveDemand/secret
      -
        routePath: /subscribe
        _controller: 'Abo::create'
    defaultController: 'Abo::new'
routes:
  -
    route: favicon.ico
    type: uri
    source: '/typo3conf/ext/ffpi_theme/Resources/Public/favicon.ico'
  -
    route: favicon.svg
    type: uri
    source: '/typo3conf/ext/ffpi_theme/Resources/Public/favicon.svg'
