base: 'http://nic.ffpi'
baseVariants:
  -
    base: 'http://nic.ffpi.local'
    condition: 'applicationContext == "Development"'
errorHandling: {  }
languages:
  -
    title: Deutsch
    enabled: true
    base: /
    typo3Language: de
    locale: de_DE.UTF-8
    iso-639-1: de
    navigationTitle: Deutsch
    hreflang: de-DE
    direction: ''
    flag: de
    languageId: '0'
rootPageId: 102
routes: {  }
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    map:
      .html: 0
      sitemap.xml: 1533906435